### ISSUE TITLE
微信读书导入不完善

### ISSUE THREAD

**Issue by Jiang10086** [it5200/flomoPlugin#12]
1.我导入了一下，发现只有标注（标记的文字）导入进来了，而没有笔记（自己写下的想法）
2.微信群二维码过期了，求更新
3.请问有在考虑导入kindle笔记吗？

**Comment by it5200** [comment]
第一个我今天看了下微信只有划线的

第二个是
![image](https://user-images.githubusercontent.com/19451694/109585375-62296180-7b3e-11eb-9e9d-3e11226c4dc7.png)

第三个昨天公众好做了下投票，今天看下结果在下结论

**Comment by it5200** [comment]
v1.1.9微信读书支持导入个人想法
