### ISSUE TITLE
希望 chrome 插件增加一键发布到其他平台的功能，如即刻、知乎想法

### ISSUE THREAD

**Issue by simon-xia** [it5200/flomoPlugin#14]
在发布一条 flomo 的同时发布到即刻、知乎想法等地方。以此实现在自己记录想法的同时，也有公共的空间引起讨论

**Comment by simon-xia** [comment]
> 这种应该是不鼓励的行为

现在 flomo 也能够以卡片的形式分享，直接发布到其他平台只是形式上的不同。再者，flomo 本身是笔记形式的工具，分享到其他社交平台和它的主战场并不冲突，为什么不鼓励。从记录想法本身的角度，我觉得反而应该鼓励，因为一个人的想法很有限，有其他角度的评论和反馈才更有意义

**Comment by kokdemo** [comment]
主要是即刻知乎也没有对应的接口吧……

**Comment by it5200** [comment]
不做支持
