### ISSUE TITLE
更新后的memo卡片平铺希望可以切换样式

### ISSUE THREAD

**Issue by wenhtlx** [it5200/flomoPlugin#15]
希望可以支持切换三瀑布流（改版后的现状）
和单瀑布流（改版前）
发现目前的宽度切分是三等分的，文本长度不一的话三瀑布流布局体验并不是特别良好

**Comment by it5200** [comment]
最新版本已经实现并上线https://chrome.google.com/webstore/detail/flomoplus/kcijjmomofpdcpeiagibojhjifhegepj?hl=zh-CN
