### ISSUE TITLE
网页上选择文字后右键没有了“send to flomo”选项

### ISSUE THREAD

**Issue by summiry** [it5200/flomoPlugin#17]
前几天还有的，今天突然没有了，没法剪藏选中文字，只能剪藏网址

**Comment by it5200** [comment]
请下载最新的包，https://github.com/it5200/flomoPlugin/releases/tag/v1.1.9，昨天已经修复

**Comment by it5200** [comment]
下次出现这个情况，可以参考下图标红部分，点击解决(需要确保是最新版本)
![image](https://user-images.githubusercontent.com/19451694/110301249-d11d2380-8032-11eb-80f4-99821847dfe6.png)
