### ISSUE TITLE
需求申请：全屏最大化输入框

### ISSUE THREAD

**Issue by iterryzhao** [it5200/flomoPlugin#18]
希望能支持全屏最大化输入框的模式
可以一键进入，沉浸式输入😆
现在的输入真的太小了，碎片输入没问题，但是写着写着就容易感觉小……

感谢~

**Comment by plidezus** [comment]
不鼓励的行为

**Comment by it5200** [comment]
最新版本已经上线https://chrome.google.com/webstore/detail/flomoplus/kcijjmomofpdcpeiagibojhjifhegepj?hl=zh-CN

**Comment by iterryzhao** [comment]
这个能力下掉了么? 我的版本是2.1.5.。。。
另一个浏览器装2.1.4是有的

**Comment by extrastu** [comment]
> 这个能力下掉了么? 我的版本是2.1.5.。。。 另一个浏览器装2.1.4是有的

flomo 支持了专注模式，所以这个下掉了，下个版本会恢复
