### ISSUE TITLE
Need instructions to install flomo plugin for utools manually

### ISSUE THREAD

**Issue by woodwm** [it5200/flomoPlugin#2]
The version of flomo plugin in utools store is very old and does not work. Need instructions to install the new version manually or update it to the official store.

**Comment by it5200** [comment]
ok

**Comment by it5200** [comment]
[ab60bd7f-0.0.4.upx.zip](https://github.com/it5200/flomoPlugin/files/5877123/ab60bd7f-0.0.4.upx.zip)
