### ISSUE TITLE
导入微博动态一直在loading

### ISSUE THREAD

**Issue by 404LT** [it5200/flomoPlugin#26]
![image](https://user-images.githubusercontent.com/8578596/113375250-97290e00-93a1-11eb-9e3f-5dcc480baa4d.png)

作者你好，在使用flomoplus导入微博的时候，一直在loading呢，请问是哪里没设置对么

**Comment by it5200** [comment]
呃，我先看下我的是否正常，稍后回复你

**Comment by naruhodo-cc** [comment]
我也有同样的问题

**Comment by it5200** [comment]
好的

**Comment by it5200** [comment]
看了下是微博改了，我这边处理下

**Comment by it5200** [comment]
已经修复，麻烦等新版本发布

**Comment by it5200** [comment]
[flomoplus-v1.3.7.zip](https://github.com/it5200/flomoPlugin/files/7019936/flomoplus-v1.3.7.zip)
新版本体验版已经修复，可以先用用
