### ISSUE TITLE
无法设置自定义标签

### ISSUE THREAD

**Issue by rainyear** [it5200/flomoPlugin#27]
设置了自定义标签，点击工具栏仍然是默认的 #Edge 

<img width="352" alt="flomoplus_debug_0" src="https://user-images.githubusercontent.com/3953966/113562188-3f580480-9638-11eb-9b9e-ad25d69ef9ea.PNG">
<img width="272" alt="flomoplus_debug_1" src="https://user-images.githubusercontent.com/3953966/113562191-4121c800-9638-11eb-8f9a-673fa63e6a4a.PNG">

**Comment by it5200** [comment]
需要保存下然后刷新下页面即可

**Comment by rainyear** [comment]
确定已保存，刷新，重新进入API设置页面，都是自定义的标签；但是回到其它页面使用时依然是默认的 ` #Edge`

**Comment by it5200** [comment]
呃呃，我现在明白了，目前线上版本就是这样的(之所以这样是考虑到这个地方可以修改，所以没有做同步，下个版本我加下)
