### ISSUE TITLE
Bug-谷歌人机验证页，会弹出两个浮动按钮

### ISSUE THREAD

**Issue by bao1956** [it5200/flomoPlugin#30]
![image](https://user-images.githubusercontent.com/9139148/114181833-93ceed00-9974-11eb-97aa-5c408b886007.png)

**Comment by it5200** [comment]
好的，已知问题，暂时无解

**Comment by zsh065400** [comment]
boss直聘也出现同样问题
![image](https://user-images.githubusercontent.com/8401093/119285404-8b0c4f00-bc74-11eb-942f-2f4e51787a40.png)

**Comment by it5200** [comment]
这个暂时误解，如果感觉有点烦人，可以去设置页设置白名单
