### ISSUE TITLE
B站消息下拉菜单出现额外的button元素

### ISSUE THREAD

**Issue by kagaya85** [it5200/flomoPlugin#33]
b站消息下拉菜单里出现了意外的button
<img width="420" alt="CleanShot_2021-04-17_at_12 15 42@2x" src="https://user-images.githubusercontent.com/28755005/115101439-bebdd000-9f76-11eb-9b0c-fa95d1298632.png">

看了下是iframe里多了这么一块元素：
<img width="449" alt="CleanShot_2021-04-17_at_12 18 31@2x" src="https://user-images.githubusercontent.com/28755005/115101482-1ceab300-9f77-11eb-9be8-60431c098ffa.png">

删除插件后恢复正常

**Comment by suiyi8760** [comment]
+1

**Comment by suiyi8760** [comment]
另外设置规则之后点保存，规则会清空，并且没有生效，图标无处不在只能先暂时关掉插件了

**Comment by it5200** [comment]
这个暂时无解，设置了规则无效的问题，如果访问的网站有iframe嵌入的话，需要吧ifram嵌入的域名填入即可
