### ISSUE TITLE
B站消息会出按钮

### ISSUE THREAD

**Issue by awesomecat2020** [it5200/flomoPlugin#34]
![image](https://user-images.githubusercontent.com/35870347/116766864-5df6c300-aa5f-11eb-98ac-c5ceb3291287.png)

**Comment by it5200** [comment]
这个暂时误解，如果感觉有点烦人，可以去设置页设置白名单

**Comment by virgoone** [comment]
判断是否在iframe就好了🤔 或者让图标可拖拽位置
