### ISSUE TITLE
Plugin 一直认为我没有登录 flomo

### ISSUE THREAD

**Issue by moyicat** [it5200/flomoPlugin#38]
<img width="675" alt="Screen Shot 2021-06-06 at 2 20 39 PM" src="https://user-images.githubusercontent.com/2023450/120940481-62537300-c6d2-11eb-9c13-39742ae24f78.png">

如图，无法获取 tags ，无法保存设置，但是我是已经登录了 flomo 网页端并且可以看到 API 的。重启 Chrome 也无效。

MacOS version: 10.15.7
Chrome version: Version 91.0.4472.77 (Official Build) (x86_64)

另外，在未登录状态下，仍然可以使用 memo 的快捷输入，之后没有任何错误提示…希望可以在这样的时候提示错误并将我刚才输入的内容复制到剪贴板。

**Comment by it5200** [comment]
刷新下网页试试

**Comment by moyicat** [comment]
谢谢，解决了～
