### ISSUE TITLE
是否考虑支持自定义标签或选择特定标签？

### ISSUE THREAD

**Issue by zwz1437** [it5200/flomoPlugin#4]

**Comment by zwz1437** [comment]
“安装后，在 chrome 中选择内容后，右键打开菜单，可以快捷保存至 flomo 并添加 #chrome 标签”，这里是添加固定的一个标签，如果能提供选择标签，会更加方便

**Comment by it5200** [comment]
设置页可以修改默认标签，去下载最新版本 https://github.com/it5200/flomoPlugin/releases

**Comment by zwz1437** [comment]
我现在使用的是最新的版本哦，设置了默认标签，但之后每次的保存都是同一个标签，如果可以根据实际的内容选择不同的标签会更好

**Comment by it5200** [comment]
呃呃，这个之前实现了一个版本(有些问题，就是不能选中文本，只能保存这个页面，所以没有加上去)
