### ISSUE TITLE
网页插件浮层图标无法显示图片

### ISSUE THREAD

**Issue by inside-ziwu** [it5200/flomoPlugin#43]
![image](https://user-images.githubusercontent.com/36299167/121980374-66f8e500-cdbe-11eb-9d76-51e0cc36254e.png)
网页插件浮层图标无法加载图片
已尝试方法：

- 卸载重装

- 右击图片加载

**Comment by it5200** [comment]
好的，刚刚看了下是chrome商店的包更新错了
