### ISSUE TITLE
问题：Twitter 网页版中，点击 flomo 按钮后，保存到 flomo 中的内容和链接是错误的

### ISSUE THREAD

**Issue by elephi** [it5200/flomoPlugin#45]
点击：
![image](https://user-images.githubusercontent.com/1418703/123446443-ccc04a80-d5d0-11eb-99fb-5372c7330a19.png)

回到 flomo：
![image](https://user-images.githubusercontent.com/1418703/123446410-c205b580-d5d0-11eb-8b8c-b0de5788fcf9.png)

可见内容为空，链接指向 twitter 首页

**Comment by it5200** [comment]
图片通过这种方式是不行的，如果需要收藏图片，请更新到最新版本然后右键同步图片到flomo
![image](https://user-images.githubusercontent.com/19451694/123578244-fadb9f80-d807-11eb-8812-d29663bda453.png)

**Comment by elephi** [comment]
> 图片通过这种方式是不行的，如果需要收藏图片，请更新到最新版本然后右键同步图片到flomo
> ![image](https://user-images.githubusercontent.com/19451694/123578244-fadb9f80-d807-11eb-8812-d29663bda453.png)

谢谢，不过我的意思不是要保存图片，只需要保存这个推的内容（正文文本）和这个推本身的完整链接。

**Comment by it5200** [comment]
目前我看到的截图里的tweet就是一张图片，目前未对图片做处理，所以是这样的

**Comment by elephi** [comment]
谢谢，可能是我描述不够精确。刚才测试发现文本的确可以保存，但是链接不是原推的。

![image](https://user-images.githubusercontent.com/1418703/123610291-5dc53a80-d7f8-11eb-8570-32d06c2f8e1d.png)

**Comment by it5200** [comment]
好的，我看下

**Comment by elephi** [comment]
> 好的，我看下

谢谢！

**Comment by it5200** [comment]
我看了下未找到tweet的链接就默认是https://twitter.com/home

**Comment by elephi** [comment]
是无法找到这条 tweet 的链接？那是否有办法能找到呢？我看 Pocket 可以做到。

多谢！

**Comment by it5200** [comment]
好的

**Comment by elephi** [comment]
感谢你的工作！

**Comment by it5200** [comment]
[flomoplus-v1.3.2.zip](https://github.com/it5200/flomoPlugin/files/6725270/flomoplus-v1.3.2.zip)

这个版本已经修复，商店等下次更新

**Comment by elephi** [comment]
Many thanks for your sharp fix!

太牛了！

**Comment by it5200** [comment]
好高兴能帮你
