### ISSUE TITLE
Dark模式可否提供切换选项

### ISSUE THREAD

**Issue by smell-well** [it5200/flomoPlugin#59]
我虽然很喜欢使用Dark模式，但有时需要正常模式，不知道是否本身有这个开关，如果没有，希望后续能加入一下

**Comment by smell-well** [comment]
我已经找到了开关暗黑模式的入口，但是仍存在一个问题是似乎没有保存记录的功能。每一次都需要重新开启还是比较麻烦的（另设置中跟随系统选项的功能似乎不能生效，浏览器无论是默认还是暗黑都是flomo都是显示暗黑模式。

**Comment by it5200** [comment]
好的，flomo现在自带有dark模式，新版本打算移除插件自带的dark

**Comment by smell-well** [comment]
> 好的，flomo现在自带有dark模式，新版本打算移除插件自带的dark

方便问一下 自带的dark模式入口在哪里么。。

**Comment by it5200** [comment]
> > 好的，flomo现在自带有dark模式，新版本打算移除插件自带的dark
> 
> 方便问一下 自带的dark模式入口在哪里么。。

flomo 设置-账号详情-偏好设置

![image](https://user-images.githubusercontent.com/19451694/130195426-e6ac4811-9a0e-4086-bc7b-9aca48b412b7.png)

**Comment by it5200** [comment]
[flomoplus-v1.3.7.zip](https://github.com/it5200/flomoPlugin/files/7019930/flomoplus-v1.3.7.zip)
给你一个新版本体验下，还没送审核
