### ISSUE TITLE
微信读书导入时，章节名期望作为书名的次级标签展示

### ISSUE THREAD

**Issue by zhangshiqin** [it5200/flomoPlugin#60]
【期望】章节名作为书名的次级标签展示
【示例】#微信读书/非暴力沟通/道德评判 这样
【原因】方便按照章节进行梳理分类，因为每一本书做的划线和笔记都比较多，按章节区分一下比较好找和总结

**Comment by it5200** [comment]
好的，谢谢反馈

**Comment by it5200** [comment]
![image](https://user-images.githubusercontent.com/19451694/130012780-de49ed7f-2aed-4a07-946e-8e58422f0cc7.png)
已经修改，下个版本更新就可以用了

**Comment by zhangshiqin** [comment]
> ![image](https://user-images.githubusercontent.com/19451694/130012780-de49ed7f-2aed-4a07-946e-8e58422f0cc7.png)
> 已经修改，下个版本更新就可以用了

下个版本什么时候更新呀

**Comment by it5200** [comment]
> > ![image](https://user-images.githubusercontent.com/19451694/130012780-de49ed7f-2aed-4a07-946e-8e58422f0cc7.png)
> > 已经修改，下个版本更新就可以用了
> 
> 下个版本什么时候更新呀

今晚送审，可以先用下 v1.3.7 beta版本
[flomoplus-v1.3.7.zip](https://github.com/it5200/flomoPlugin/files/7020240/flomoplus-v1.3.7.zip)
