### ISSUE TITLE
chrome 强制取代新标签页，如何取消？

### ISSUE THREAD

**Issue by buildaworld** [it5200/flomoPlugin#63]
设置界面与之前无变化，未找到相关设置项

**Comment by it5200** [comment]
在浏览器设置-默认浏览器-启动时 ，停用flomoplus 就可以了

**Comment by it5200** [comment]
抱歉啊，下个版本去掉

**Comment by buildaworld** [comment]
停用整个扩展就停了
我先暂时关了，希望尽快更新，扩展本身还是挺好用的

**Comment by it5200** [comment]
> 还是

好的

**Comment by it5200** [comment]
可以先使用1.3.8版本，1.3.8版本下载https://github.com/it5200/flomoPlugin/releases/tag/1.3.8
