### ISSUE TITLE
打开新网页时更改了浏览器主页&登入新网址需要刷新一次才能使用flomo插件。

### ISSUE THREAD

**Issue by ylzty** [it5200/flomoPlugin#64]

**Comment by it5200** [comment]
好的，收到，造成不便，抱歉，我正在去掉这个newtab

**Comment by it5200** [comment]
可以先使用1.3.8版本，1.3.8版本下载https://github.com/it5200/flomoPlugin/releases/tag/1.3.8

**Comment by Jface001** [comment]
+1 , 希望可以自定义是否启动NewTab
同时发现更新说明被折叠, 不知是否是特例?
![Chrome拓展页面截图](https://user-images.githubusercontent.com/21217483/130307812-a22bccd7-43b5-46e8-940d-8ce2b335701d.png)

**Comment by it5200** [comment]
> +1 , 希望可以自定义是否启动NewTab
> 同时发现更新说明被折叠, 不知是否是特例?
> ![Chrome拓展页面截图](https://user-images.githubusercontent.com/21217483/130307812-a22bccd7-43b5-46e8-940d-8ce2b335701d.png)

这个是正常的，正常情况下是新页面打开这个view的
