### ISSUE TITLE
查看拓展插件-选项 更新内容弹窗显示不正确

### ISSUE THREAD

**Issue by Jface001** [it5200/flomoPlugin#66]
Chrome浏览器右键查看拓展插件-选项 更新内容弹窗显示不正确
不晓得是否是个例, 我查看其它拓展没有发现此问题(也可能他们选项转跳页面都不一样?)

![Chrome拓展页面截图](https://user-images.githubusercontent.com/21217483/130307812-a22bccd7-43b5-46e8-940d-8ce2b335701d.png)

**Comment by it5200** [comment]
首先感谢，然后这个是正常的现象，一般是新页面打开这个view

**Comment by Jface001** [comment]
> 首先感谢，然后这个是正常的现象，一般是新页面打开这个view
好的~ 但是这个更新内容就完全看不见, 无法拖动放大拉宽等等....

**Comment by it5200** [comment]
好的，我优化下
