### ISSUE TITLE
网页右下角的按钮影响到了正常使用网页的功能

### ISSUE THREAD

**Issue by zhangshiqin** [it5200/flomoPlugin#69]
![image](https://user-images.githubusercontent.com/6120958/130717045-de80133b-76b6-4ad7-a240-eea7a4997da9.png)

如图，它遮住了一些网页原本在右下角的功能按钮

请问是否可以提供关闭这个快捷按钮的方式

**Comment by it5200** [comment]
后台设置可以关闭

**Comment by zhangshiqin** [comment]
> 后台设置可以关闭

找到了，我以为这里只是纯设置 API 的地方，也许可以改一下这个入口的文案，或者把设计 API 和网页批注的功能分开

**Comment by it5200** [comment]
好的

**Comment by it5200** [comment]
![image](https://user-images.githubusercontent.com/19451694/130719633-948548ac-c5eb-4dce-930c-5bf0d169d8a7.png)
新版修改，为了不遮挡原网页可以删除，需要使用时再刷新就可以看到
