### ISSUE TITLE
需求反馈：希望新增得到的笔记同步

### ISSUE THREAD

**Issue by ForestFDemo** [it5200/flomoPlugin#9]
## 背景

目前电子书使用的主流有 2 个：微信读书和得到电子书；

微信读书目前同步 flomo 很好用；得到的笔记现在是同步到印象笔记，且格式很不友好（一次性全部同步了），而且需要从印象笔记同步到flomo，流程较多。

## 诉求

希望新增得到的电子书笔记、课程笔记的同步。

感谢。

**Comment by it5200** [comment]
v1.1.8版本已经实现

**Comment by ForestFDemo** [comment]
希望能同步得到的课程笔记。
